main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name="index"),
    path('register', views.register, name="register"),
    path('my-login', views.my_login, name="my-login"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('user-logout', views.user_logout, name="user-logout"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from django import forms
from django.forms.widgets import PasswordInput, TextInput


# Create/Register a user (Model Form)

class CreateUserForm(UserCreationForm):
    
    class Meta:
        
        model = User
        fields = ['username', 'email', 'password1', 'password2']


# Authenticate a user (Model Form)

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

main/views.py
from django.shortcuts import render, redirect
from . forms import CreateUserForm, LoginForm

from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

# Create your views here.


def homepage(request):
    return render(request, 'main/index.html')


def register(request):

    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("./my-login")

    context = {'registerform' :form}

    return render(request, 'main/register.html', context=context)


def my_login(request):

    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth.login(request, user)
                return redirect("./dashboard")
    
    context = {'loginform' :form}

    return render(request, 'main/my-login.html', context=context)

def user_logout(request):
    auth.logout(request)
    return redirect("./")


@login_required(login_url="./my-login")
def dashboard(request):
    return render(request, 'main/dashboard.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza

# Create your views here.

# /menu
def index(request):
    '''pizzas = Pizza.objects.all()
    pizzas_names_and_prices = [pizza.nom + " : " + str(pizza.prix) + "$" for pizza in pizzas]
    pizzas_names_and_prices_str = ", ".join(pizzas_names_and_prices)
    return HttpResponse("Les pizzas : " + pizzas_names_and_prices_str)'''
    pizzas = Pizza.objects.all().order_by('prix')
    return render(request, 'menu/index.html', {'pizzas' : pizzas})


def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

main/templates/main/dashboard.html
<html>
    <h1>This is my dashbard</h1>

    <a href="{% url 'main:user-logout' %}">Logout</a>


</html>

main/templates/main/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">

</head>
<body>
    <div class="centered">
        <img id="main_logo" src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">View menu</a>
        <a href="{% url 'main:register' %}">Register for free</a>
        <a href="{% url 'main:my-login' %}">Sign in</a>
    </div>
</body>
</html>

main/templates/main/my-login.html
<html>
    <head>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>  

        <a href="{% url 'main:index' %}">Back</a>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <h2 class="mb-4">Login</h2>
                    <form id="loginForm" method="POST">

                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>

    </body>

</html>

main/templates/main/register.html
<html>
   
    <body>

        <a href="{% url 'main:index' %}">Back</a>

        <h1>Register now!</h1>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            {{registerform.as_p}}

            <input type="submit" value="Register">

        </form>

    </body>


</html>

menu/templates/menu/index.html
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>
    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>
    <div class="menu_list">
        {% for pizza in pizzas %}
            <div class="menu_list_item">
                <span class="menu_list_title">{{pizza.nom}}</span>
                <span class="menu_list_price">{{pizza.prix | floatformat:2}}$</span>
                <span class="menu_list_ingredients">{{pizza.ingredients}}$</span>
                {% if pizza.vegetarienne %}
                <span class="menu_list_badge">VEGETARIENNE</span>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</body>
</html>